name = "<PROJECT_NAME>"
main = "./dist/_worker.js/index.js"
compatibility_date = "2025-06-30"
compatibility_flags = ["nodejs_compat"]

[assets]
binding = "ASSETS"
directory = "./dist"

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "<DATABASE_NAME>"
database_id = "<DATABASE_ID>"
migrations_dir = "drizzle"

[[unsafe.bindings]]
name = "COMMENT_LIMIT"
type = "ratelimit"
namespace_id = "0001"
simple = { limit = 2, period = 10 }
